# Generated by Django 4.0.6 on 2022-10-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=16)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=13)),
                ('customer_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UntisTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=16)),
                ('units', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'BUY'), ('BORROW', 'BORROW')], default='BUY', max_length=30)),
                ('amount', models.CharField(max_length=15)),
                ('interest', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=20)),
                ('Metertoken', models.CharField(max_length=16)),
                ('PaymentToken', models.CharField(max_length=16)),
                ('RemaingBalance', models.CharField(max_length=16)),
                ('PiadBalance', models.CharField(max_length=16)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('is_paid', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ElectriLendigSystem.customers')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ElectriLendigSystem.customers')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=14)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ElectriLendigSystem.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ElectriLendigSystem.customers')),
            ],
        ),
    ]
